# The superuser
u root    0     "Super User" /root

# Well-known numbered group name from /etc/group

g bin     1    -             -
g daemon  2    -             -
g sys     3    -             -
g adm     4    -             -
g tty     5    -             -
g disk    6    -             -
g lp      7    -             -
g mem     8    -             -
g kmem    9    -             -
g mail    12   -             -
g utmp    22   -             -
g kvm     23   -             -
g uucp    24   -             -
g cdrom   25   -             -
g floppy  26   -             -
g audio   27   -             -
g video   28   -             -
g input   29   -             -
g proc    30   -             -
g nogroup 99   -             -

# The nobody user/group for NFS file systems
g nobody 65534       -            -
u nobody 65534:65534 "Kernel Overflow User"     -

# Administrator group: can *do* more than normal users
g wheel   -     -            -

# Physical and virtual hardware access groups
g optical -     -            -
g render  -     -            -
g sgx     -     -            -
g storage -     -            -

# Default group for normal users
g users   -     -            -
