# Maintainer: Yao Zi <me@ziyao.cc>

pkgname=freecad
pkgver=1.0.2
pkgrel=1
pkgdesc='Free multiplatform 3D parametric modeler'
url='https://www.freecad.org'
arch=(x86_64 aarch64 riscv64 loongarch64)
license=(LGPL-2.0-or-later)
depends=(musl yaml-cpp libspnav vtk zlib-ng xerces-c llvm-libs onetbb python
	 libspnav med openmp freetype2 fmt boost-libs qt6-base qt6-tools qt6-svg
	 libglvnd glu coin pyside6 python-pivy)
makedepends=(cmake doxygen boost shiboken6)
# Too many ODR violations to enable LTO :(
# https://github.com/FreeCAD/FreeCAD/issues/13173
options=(!lto)
# 0001: Downstream, don't look for Boost::system which is dropped by 1.89.
#	Upstream commit 0f6d00d2a547 ("fix issue #23829 build with boost v1.89 and greater")
#	resolved the issue, but couldn't be backporte to 1.0.x.
# 0003: Backport 39ca75bac294 ("Py3.13: Update PyCXX to version 7.1.11")
#	to fix PyCXX compatibility with libc++ 20, which deprecated
#	instantiation of std::basic_string<> against non-character types since
#	it's considered UB by LWG 2994.
# 0004: Backport 692d40916a61 ("Py3.13: Disable Py_UNICODE support in PyCXX"),
#	Py_UNICODE has been deprecated in Python since 3.13
#	Reference: https://github.com/python/cpython/issues/105156
# Note 0003 and 0004 are manually patched with s%3rdParty/PyCXX/%%g, as PyCXX
# source is moved from src to src/3rdParty/PyCXX.
# 0005: Backports, fix compatibility issues with VTK 9.6, consists multiple
#	upstream commits,
#
#	3d2b7dc9c7ac Use vtkUnstructuredGrid::GetLinks instead of vtkUnstructuredGrid::GetCellLinks for VTK >= 9.3
#	261ca3905b47 Smesh: patch other VTK UG deprecations
#	3a68d91ae306 smesh: update for VTK 9.6 Types array
#	ff3e419d2ea4 smesh: update for VTK 9.4 polyhedron rework
#	6d4ce9e9b849 Remove usages of non thread-safe vtkUnstructuredGrid::GetFaceStream
#	c9acda2a659f Standardize VTK version check pre-processing directives
#	bd90728f886b Smesh: Remove the VTK_CELL_ARRAY_V2 compatibility define
#
#	mostly generated by
#
# (git format-patch --stdout -1 3d2b7dc9c7ac898b30fe469b7cbd424ed1bca0a2;
#  git format-patch --stdout 261ca3905b47b251b0751fd7af45ad5c3fd129e4 -6)
#
#	Manually edited parts are annoted in the patch.
# 0006: Should be upstreamed, avoid including execinfo.h which is glibc-specific
# 0007: Should be upstreamed, dropping usage of *ARB API for vertex_array_object,
#	which has been standard profile since OpenGL 1.5
# 0008: Backport 8547e798fb3b ("CMake: Fix Eigen3 version search")
#	Fix detection logic compatibility with Eigen 5.x
# 0009: Backport b3e8ed7814ac ("Gui/Application, QuarterWidget: request OpenGL compatibility profile (#23768)")
#	Fix 3D view rendering under Wayland. Qt by default requests a context
#	with OpenGL ES API, while FreeCAD requires OpenGL and compatibility
#	profile, causing API errors in glMatrixMode() etc.
source=("https://github.com/FreeCAD/FreeCAD/releases/download/$pkgver/freecad_source.tar.gz"
	0001-Drop-Boost-system.patch
	0002-Link-libOpenGL-instead-of-libGL.patch
	0003-Py3.13-Update-PyCXX-to-version-7.1.11.patch
	0004-Py3.13-Disable-Py_UNICODE-support-in-PyCXX.patch
	0005-VTK-9.6-compatiblity-fixes.patch
	0006-do-not-include-execinfo.patch
	0007-Mod-Part-Do-not-use-ARB-API.patch
	0008-CMake-Fix-Eigen3-version-search.patch
	0009-Gui-Application-QuarterWidget-request-OpenGL-compati.patch)
sha256sums=('c9b8e19dbf20cea387c432890ea059059ff6b57ec4cd77820cd1202d1247bbde'
            '8adaeb92a094ac9aa067799f55476bae3c32e6b662f1a7d152ec3e9a9337c0c9'
            'e95d21b28a4cface0365d14636a1f3d6e9f3c4933dc1c0879795903efcbe87bf'
            'ad078224681c671055ba64ad7698e93836ca80ba64aedd245033ea38de3aaa5d'
            '145b118b2ccd5e726a5987d83378f84ab11e82eff53b9c411ff7306911e4b112'
            '2794ab584c1af1d7cb3e2d6f9609664328bebc4daf5e7c51460734d2ee79c913'
            '0df1d4f0108cf5ec2db2ca8ed4fcf07049f56d92b5fbbeb48f419748004340e9'
            '755f16e0356913b972ba6cc7c66d0f4fc11c023db1ca0838db31923607a5ba0d'
            'c67c75a00f879330830b064d7fb20993f35460e2ff9149d2a29ce3d7d2e0a71d'
            '84bec627f1910149e11168921c598943fb7d60735fb3e4db9f6f4cbf9118e4c8')

prepare() {
	_patch_ .
}

build() {
	# BUILD_VR: missing Rift
	# CMAKE_INSTALL_* is to work around the weird installation paths.
	cmake -S . -B pkgbuild -Wno-dev \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo		\
		-DCMAKE_INSTALL_BINDIR=/usr/lib/freecad/bin	\
		-DCMAKE_INSTALL_DATADIR=/usr/share/freecad	\
		-DCMAKE_INSTALL_DATAROOTDIR=/usr/share		\
		-DCMAKE_INSTALL_DOCDIR=/usr/share/doc		\
		-DCMAKE_INSTALL_LIBDIR=/usr/lib/freecad/lib	\
		-DCMAKE_INSTALL_PREFIX=/usr/lib/freecad		\
		-DINSTALL_TO_SITEPACKAGES=ON			\
		-DOPENGL_GL_PREFERENCE=GLVND			\
		-DOPENGL_USE_GLES2=ON				\
		-DOPENGL_USE_OPENGL=ON				\
		-DOPENGL_USE_GLX=OFF				\
		-DOPENGL_USE_EGL=ON				\
		-DBUILD_GUI=ON					\
		-DBUILD_VR=OFF					\
		-DENABLE_DEVELOPER_TESTS=OFF

	cmake --build pkgbuild
}

package() {
	DESTDIR="$pkgdir" cmake --install pkgbuild

	install -dm755 "$pkgdir"/usr/bin
	ln -s ../lib/freecad/bin/FreeCAD "$pkgdir"/usr/bin/FreeCAD
}
