#!/bin/sh -e
pre_install() {
    touch /var/log/wtmp
    chown utmp:utmp /var/log/wtmp
    chmod 0640 /var/log/wtmp
}

post_install() {
    if [ -d /etc/dinit.d/boot.d ] ; then
        ln -s ../utmpd /etc/dinit.d/boot.d/utmpd
        ln -s ../wtmpd /etc/dinit.d/boot.d/wtmpd
    fi
}

pre_remove() {
    if [ -d /etc/dinit.d ] ; then
        rm -f /etc/dinit.d/boot.d/utmpd
        rm -f /etc/dinit.d/boot.d/wtmpd
    fi
}

post_remove() {
    rm -rf /run/utmps
}
